name: CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4

      - name: Build project
        run: make setup

      - name: Run linter
        run: make lint

      - name: Run tests
        run: make test

      - name: Print Hello from Hexlet
        uses: hexlet-components/hello-from-hexlet-action@release
