name: test-and-lint

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3

      - name: Build project
        run: make setup

  test-lint:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Run tests
        run: make test
